const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    // admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    //position 
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    //role
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //SAVE BTN
    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    //EDIT
    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    //FETCH ALL USER
    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    //delete user
    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    //top doctor home
    FETCH_TOP_DOCTORS_START: 'FETCH_TOP_DOCTORS_START',
    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    //all doctors
    FETCH_ALL_DOCTORS_START: 'FETCH_ALL_DOCTORS_START',
    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

    //save infor doctors
    SAVE_DETAIL_DOCTOR_START: 'SAVE_DETAIL_DOCTOR_START',
    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    //all code schedule time
    FETCH_ALLCODE_SCHEDULE_TIME_START: 'FETCH_ALLCODE_SCHEDULE_TIME_START',
    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    //required doctor infor
    FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAILED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAILED',

    //clinic
    FETCH_ALL_CLINIC_START: 'FETCH_ALL_CLINIC_START',
    FETCH_ALL_CLINIC_SUCCESS: 'FETCH_ALL_CLINIC_SUCCESS',
    FETCH_ALL_CLINIC_FAILED: 'FETCH_ALL_CLINIC_FAILED',

    DELETE_A_CLINIC_START: 'DELETE_A_CLINIC_START',
    DELETE_A_CLINIC_SUCCESS: 'DELETE_A_CLINIC_SUCCESS',
    DELETE_A_CLINIC_FAILED: 'DELETE_A_CLINIC_FAILED',

    EDIT_A_CLINIC_START: 'EDIT_A_CLINIC_START',
    EDIT_A_CLINIC_SUCCESS: 'EDIT_A_CLINIC_SUCCESS',
    EDIT_A_CLINIC_FAILED: 'EDIT_A_CLINIC_FAILED',

    //HANDBOOK
    FETCH_ALL_HANDBOOK_START: 'FETCH_ALL_HANDBOOK_START',
    FETCH_ALL_HANDBOOK_SUCCESS: 'FETCH_ALL_HANDBOOK_SUCCESS',
    FETCH_ALL_HANDBOOK_FAILED: 'FETCH_ALL_HANDBOOK_FAILED',

    DELETE_A_HANDBOOK_START: 'DELETE_A_HANDBOOK_START',
    DELETE_A_HANDBOOK_SUCCESS: 'DELETE_A_HANDBOOK_SUCCESS',
    DELETE_A_HANDBOOK_FAILED: 'DELETE_A_HANDBOOK_FAILED',

    EDIT_A_HANDBOOK_START: 'EDIT_A_HANDBOOK_START',
    EDIT_A_HANDBOOK_SUCCESS: 'EDIT_A_HANDBOOK_SUCCESS',
    EDIT_A_HANDBOOK_FAILED: 'EDIT_A_HANDBOOK_FAILED',

    //SPECIALTY
    FETCH_ALL_SPECIALTY_START: 'FETCH_ALL_SPECIALTY_START',
    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',

    DELETE_A_SPECIALTY_START: 'DELETE_A_SPECIALTY_START',
    DELETE_A_SPECIALTY_SUCCESS: 'DELETE_A_SPECIALTY_SUCCESS',
    DELETE_A_SPECIALTY_FAILED: 'DELETE_A_SPECIALTY_FAILED',

    EDIT_A_SPECIALTY_START: 'EDIT_A_SPECIALTY_START',
    EDIT_A_SPECIALTY_SUCCESS: 'EDIT_A_SPECIALTY_SUCCESS',
    EDIT_A_SPECIALTY_FAILED: 'EDIT_A_SPECIALTY_FAILED',
})
export default actionTypes;